### Create reservation
POST http://localhost:3000/reservation
content-type: application/json

{
    "r_date": "04/15/2022",
    "total_amount": 1,
    "class": "Business",
    "flight": [{
        "id": 18
    }]
}

### Get all 
GET http://localhost:3000/reservation/