### Create a flight
POST http://localhost:3000/flight
content-type: application/json

{
    "flight_deptr_date": "04/19/2022",
    "deptr_country": "Viet Nam",
    "dest_country": "Singapore",
    "deptr_time": "11:15",
    "arrival_time": "12:45",
    "airline": 1
}


### Get all
GET http://localhost:3000/flight