### Register
POST http://localhost:3000/authentication/register
Content-Type: application/json

{
  "email": "tester68@gmail.com",
  "password": "tester68",
  "firstName": "Admin",
  "lastName": "Super",
  "address": "Earth",
  "dayofbirth": "01/01/2000",
  "gender": "Male",
  "phoneNumber": "0123456789"
}

### Login
POST http://localhost:3000/authentication/log-in
Content-Type: application/json

{
  "email": "tester68@gmail.com",
  "password": "tester68"
}



### Logout
POST http://localhost:3000/authentication/log-out
Content-Type: application/json



### Authentication
GET http://localhost:3000/authentication/





### Get all reservation
GET http://localhost:3000/reservation/

### Create a flight
POST http://localhost:3000/flight
content-type: application/json

{
    "flight_deptr_date": "04/19/2022",
    "deptr_country": "Viet Nam",
    "dest_country": "Singapore",
    "deptr_time": "11:15",
    "arrival_time": "12:45",
    "airline": 1
}

### Get all garage
GET http://localhost:3000/garage

### Create garage
POST http://localhost:3000/garage
content-type: application/json

{
  "name" : "Mers"
}

### Create service
POST http://localhost:3000/service
content-type: application/json

{
    "name": "Oil Change",
    "price": "500",
    "time" : "60",
    "description" : "Oil Change",
    "garage":  {
      "id": 1
    }
}


### Get All Services
GET http://localhost:3000/service


### Create reservation
POST http://localhost:3000/reservation
content-type: application/json

{
    "r_date": "01/20/2022",
    "r_time": "01:00",
    "service":  3,
    "user": 1,
    "status": 1
}

### Get reservation
 
GET http://localhost:3000/reservation