### Register
POST http://localhost:3000/authentication/register
Content-Type: application/json

{
  "email": "dweswswsdeded@gmail.com",
  "password": "admin",
  "firstName": "tester69",
  "lastName": "tester69",
  "address": "tester69",
  "dayofbirth": "01/01/2000",
  "gender": "male",
  "phoneNumber": "0123456789"
}

### Login
POST http://localhost:3000/authentication/log-in
Content-Type: application/json

{
  "email": "tester68@gmail.com",
  "password": "tester68"
}



### Logout
POST http://localhost:3000/authentication/log-out
Content-Type: application/json



### Authentication
GET http://localhost:3000/authentication/


### Create reservation
POST http://localhost:3000/reservation
content-type: application/json

{
    "r_date": "04/15/2022",
    "total_amount": 1,
    "class": "Business",
    "flight": [{
        "id": 1
    }]
}



### Get all reservation
GET http://localhost:3000/reservation/

### Create a flight
POST http://localhost:3000/flight
content-type: application/json

{
    "flight_deptr_date": "04/19/2022",
    "deptr_country": "Viet Nam",
    "dest_country": "Singapore",
    "deptr_time": "11:15",
    "arrival_time": "12:45",
    "airline": 1
}

### Get all garage
GET http://localhost:3000/garage

### Create garage
POST http://localhost:3000/garage
content-type: application/json

{
  "name" : "Mers"
}

### Create service
POST http://localhost:3000/service
content-type: application/json

{
    "name": "Tire Replacement",
    "price": "2000",
    "time" : "60",
    "description" : "Replacement 4 tires for car",
    "garage":  {
      "id": 2
    }
}

### Create reservation
POST http://localhost:3000/reservation
content-type: application/json

{
    "r_date": "01/20/2022",
    "service":  [
      {"id": 1}, 
      { "id": 2}
      ]
}

### Get reservation
 
GET http://localhost:3000/reservation